### ISSUE TITLE
Could you please include a requirements.txt file?

### ISSUE THREAD

**Issue by gessyoo** [csxmli2016/ASFFNet512#2]
I realize this project is very new, but publishing your requirements.txt would make testing the code much easier.

**Comment by csxmli2016** [comment]
> I realize this project is very new, but publishing your requirements.txt would make testing the code much easier.

Hi, thanks for your suggestions. I have added the requirements.txt. This project only needs torch, torchvision, numpy, opencv-python, face_alignment, which are very common.
