### ISSUE TITLE
Could you please provide the training dataset like CelebAHQ_Ref

### ISSUE THREAD

**Issue by hongsiyu** [csxmli2016/ASFFNet512#4]
Thx very much!

**Comment by csxmli2016** [comment]
> Thx very much!

Hi, this work is under review. Maybe I will release it before the end of September.

**Comment by csxmli2016** [comment]
> Thx very much!

Hi, I have released the CelebRef-HQ dataset. Please kindly refer to https://github.com/csxmli2016/DMDNet
