### ISSUE TITLE
Can you select specific facial landmarks only?

### ISSUE THREAD

**Issue by unknownentity123** [csxmli2016/ASFFNet512#5]
In one of your examples with Obama and Rami Malek you show eye color being transferred over from Rami to Obama....can the landmark list be filtered to only transfer eyes while leaving the rest untouched? #

**Comment by csxmli2016** [comment]
> In one of your examples with Obama and Rami Malek you show eye color being transferred over from Rami to Obama....can the landmark list be filtered to only transfer eyes while leaving the rest untouched? #
Theoretically speaking, it could achieve this task. But I think it would be better to fine-tune this model with such settings.
